displayName=No Run Hotkey
author=willzero123
description=Hold a hotkey to temporarily remove the 'Walk here' menu option
tags=menu,walk,hide,hotkey,run,misclick
version=1.0.1
plugins=com.norunhotkey.NoRunHotkeyPlugin
build=standard
